### ISSUE TITLE
Add Seed() function to API?

### ISSUE THREAD

**Issue by seletskiy** [valyala/fastrand#1]
Library is really great for benchmark purposes when one needs to generate lots of random data to feed to some procesing.

But lack of `Seed()` function makes it difficult to debug code.

**Comment by achille-roussel** [comment]
I’m open to adding this. Would you be able to send a pull request to add this?

**Comment by valyala** [comment]
Seed may be added to RNG, but it cannot be added to global rand funcs, since they depend on non-deterministic sync.Pool.
The addition of Seed to RNG would make the API incomplete and uglier.
